# This action does the following things:
# - kicks off the parser
# - writes the data to the master spreadsheet
# - sends the contact email address an email letting them know that the ENF got their application
#
# Ted Cahall 13Nov2022
#
# https://stackoverflow.com/questions/69499645/how-to-securely-allow-github-actions-to-check-pr-and-post-results-in-comment
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
#

name: Grant PR Received

# Controls when the workflow will run
on:
  pull_request_target:
    types: [synchronize]
    # types: [opened, edited, synchronize]

jobs:
  get_filename:
    runs-on: ubuntu-latest
    outputs:
      filename: ${{ steps.files.outputs.added }}
    steps:
      - name: Get application file name
        id: 'files'
        uses: Ana06/get-changed-files@v2.0.0
        with:
          filter: 'applications/*.md'

      - name: echo the file name
        id: 'file-echo'
        run: echo "The filename that changed was ${{ outputs.filename }}"

  parse_app:
    uses: ./.github/workflows/ru-big-parser.yml
    with:
      filename: "${{ needs.get_filename.outputs.filename }}"
    needs: get_filename

